### ISSUE TITLE
[Question] How did you get syntax highlighting to work?

### ISSUE THREAD

**Issue by thesofakillers** [lclem/prolog-kernel#3]
I'm currently working on building a kernel for [clingo](https://potassco.org/clingo/).
I'd like to add syntax highlighting, but unfortunately there is no codemirror support for clingo.
I see that there is no codemirror support for prolog either, which has very similar syntax.
However, i see that you have managed to have syntax highlighting in your kernel.
How? From your code I could not tell. 
Thanks!

**Comment by lclem** [comment]
this is an excellent question! weird as it may be, I have no idea, I also checked the code and it seems that nothing there contains anything related to that. perhaps in codemirror they added support for prolog? or you are running some custom codemirror?

**Comment by thesofakillers** [comment]
i think i figured it out actually. The syntax-highlighting works here on github because it uses nbconvert and that is pygments-based, and indeed there exists a pygments prolog lexer. 

I haven't tried running this kernel, but I imagine syntax highlighting is not available when actually editing files, since that uses codemirror rather than pygments. Running the kernel on binder confirms this.

Thanks anyway!
